name: Release App

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: true # Allow individual OS builds to fail
    defaults:
      run:
        shell: pwsh # Use PowerShell for all steps in this job
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            macos-13,
            macos-latest,
          ]
        include:
          - os: ubuntu-latest
            binary_suffix: linux-x64
          - os: ubuntu-24.04-arm
            binary_suffix: linux-arm64
          - os: windows-latest
            binary_suffix: windows-x64
          - os: macos-13
            binary_suffix: macos-x64
          - os: macos-latest
            binary_suffix: macos-arm
      fail-fast: false # IMPORTANT: Run all matrix entries even if some fail

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: denoland/setup-deno@v2

      - name: Set Binary Name
        id: set_binary_name
        run: |
          if ($env:RUNNER_OS -eq 'Windows') {
            echo "binary_name=deno-seal-${{ matrix.binary_suffix }}.exe" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
          else {
            echo "binary_name=deno-seal-${{ matrix.binary_suffix }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Compile App
        run: deno compile --output ${{ steps.set_binary_name.outputs.binary_name }} --no-check --config src/ui/deno.json --include src/ui/ -A src/webview/webview.ts

      - name: Upload App
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ steps.set_binary_name.outputs.binary_name }} # Use the dynamic name
          tag: ${{ github.ref_name }}
          overwrite: true # Important: Overwrite previous uploads *for the same OS*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
